# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cwood/Projects/fib-performance

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cwood/Projects/fib-performance

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cwood/Projects/fib-performance/CMakeFiles /Users/cwood/Projects/fib-performance/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cwood/Projects/fib-performance/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fib_perf

# Build rule for target.
fib_perf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fib_perf
.PHONY : fib_perf

# fast build rule for target.
fib_perf/fast:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/build
.PHONY : fib_perf/fast

#=============================================================================
# Target rules for targets named test_map

# Build rule for target.
test_map: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_map
.PHONY : test_map

# fast build rule for target.
test_map/fast:
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/build
.PHONY : test_map/fast

src/fib.o: src/fib.c.o

.PHONY : src/fib.o

# target to build an object file
src/fib.c.o:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/fib.c.o
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/fib.c.o
.PHONY : src/fib.c.o

src/fib.i: src/fib.c.i

.PHONY : src/fib.i

# target to preprocess a source file
src/fib.c.i:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/fib.c.i
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/fib.c.i
.PHONY : src/fib.c.i

src/fib.s: src/fib.c.s

.PHONY : src/fib.s

# target to generate assembly for a file
src/fib.c.s:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/fib.c.s
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/fib.c.s
.PHONY : src/fib.c.s

src/fib_cisco.o: src/fib_cisco.c.o

.PHONY : src/fib_cisco.o

# target to build an object file
src/fib_cisco.c.o:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/fib_cisco.c.o
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/fib_cisco.c.o
.PHONY : src/fib_cisco.c.o

src/fib_cisco.i: src/fib_cisco.c.i

.PHONY : src/fib_cisco.i

# target to preprocess a source file
src/fib_cisco.c.i:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/fib_cisco.c.i
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/fib_cisco.c.i
.PHONY : src/fib_cisco.c.i

src/fib_cisco.s: src/fib_cisco.c.s

.PHONY : src/fib_cisco.s

# target to generate assembly for a file
src/fib_cisco.c.s:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/fib_cisco.c.s
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/fib_cisco.c.s
.PHONY : src/fib_cisco.c.s

src/fib_naive.o: src/fib_naive.c.o

.PHONY : src/fib_naive.o

# target to build an object file
src/fib_naive.c.o:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/fib_naive.c.o
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/fib_naive.c.o
.PHONY : src/fib_naive.c.o

src/fib_naive.i: src/fib_naive.c.i

.PHONY : src/fib_naive.i

# target to preprocess a source file
src/fib_naive.c.i:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/fib_naive.c.i
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/fib_naive.c.i
.PHONY : src/fib_naive.c.i

src/fib_naive.s: src/fib_naive.c.s

.PHONY : src/fib_naive.s

# target to generate assembly for a file
src/fib_naive.c.s:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/fib_naive.c.s
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/fib_naive.c.s
.PHONY : src/fib_naive.c.s

src/fib_perf.o: src/fib_perf.c.o

.PHONY : src/fib_perf.o

# target to build an object file
src/fib_perf.c.o:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/fib_perf.c.o
.PHONY : src/fib_perf.c.o

src/fib_perf.i: src/fib_perf.c.i

.PHONY : src/fib_perf.i

# target to preprocess a source file
src/fib_perf.c.i:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/fib_perf.c.i
.PHONY : src/fib_perf.c.i

src/fib_perf.s: src/fib_perf.c.s

.PHONY : src/fib_perf.s

# target to generate assembly for a file
src/fib_perf.c.s:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/fib_perf.c.s
.PHONY : src/fib_perf.c.s

src/map.o: src/map.c.o

.PHONY : src/map.o

# target to build an object file
src/map.c.o:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/map.c.o
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/map.c.o
.PHONY : src/map.c.o

src/map.i: src/map.c.i

.PHONY : src/map.i

# target to preprocess a source file
src/map.c.i:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/map.c.i
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/map.c.i
.PHONY : src/map.c.i

src/map.s: src/map.c.s

.PHONY : src/map.s

# target to generate assembly for a file
src/map.c.s:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/map.c.s
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/map.c.s
.PHONY : src/map.c.s

src/random.o: src/random.c.o

.PHONY : src/random.o

# target to build an object file
src/random.c.o:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/random.c.o
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/random.c.o
.PHONY : src/random.c.o

src/random.i: src/random.c.i

.PHONY : src/random.i

# target to preprocess a source file
src/random.c.i:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/random.c.i
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/random.c.i
.PHONY : src/random.c.i

src/random.s: src/random.c.s

.PHONY : src/random.s

# target to generate assembly for a file
src/random.c.s:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/random.c.s
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/random.c.s
.PHONY : src/random.c.s

src/siphash24.o: src/siphash24.c.o

.PHONY : src/siphash24.o

# target to build an object file
src/siphash24.c.o:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/siphash24.c.o
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/siphash24.c.o
.PHONY : src/siphash24.c.o

src/siphash24.i: src/siphash24.c.i

.PHONY : src/siphash24.i

# target to preprocess a source file
src/siphash24.c.i:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/siphash24.c.i
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/siphash24.c.i
.PHONY : src/siphash24.c.i

src/siphash24.s: src/siphash24.c.s

.PHONY : src/siphash24.s

# target to generate assembly for a file
src/siphash24.c.s:
	$(MAKE) -f CMakeFiles/fib_perf.dir/build.make CMakeFiles/fib_perf.dir/src/siphash24.c.s
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/siphash24.c.s
.PHONY : src/siphash24.c.s

src/test/test_map.o: src/test/test_map.c.o

.PHONY : src/test/test_map.o

# target to build an object file
src/test/test_map.c.o:
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/test/test_map.c.o
.PHONY : src/test/test_map.c.o

src/test/test_map.i: src/test/test_map.c.i

.PHONY : src/test/test_map.i

# target to preprocess a source file
src/test/test_map.c.i:
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/test/test_map.c.i
.PHONY : src/test/test_map.c.i

src/test/test_map.s: src/test/test_map.c.s

.PHONY : src/test/test_map.s

# target to generate assembly for a file
src/test/test_map.c.s:
	$(MAKE) -f CMakeFiles/test_map.dir/build.make CMakeFiles/test_map.dir/src/test/test_map.c.s
.PHONY : src/test/test_map.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... fib_perf"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... test_map"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... src/fib.o"
	@echo "... src/fib.i"
	@echo "... src/fib.s"
	@echo "... src/fib_cisco.o"
	@echo "... src/fib_cisco.i"
	@echo "... src/fib_cisco.s"
	@echo "... src/fib_naive.o"
	@echo "... src/fib_naive.i"
	@echo "... src/fib_naive.s"
	@echo "... src/fib_perf.o"
	@echo "... src/fib_perf.i"
	@echo "... src/fib_perf.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/siphash24.o"
	@echo "... src/siphash24.i"
	@echo "... src/siphash24.s"
	@echo "... src/test/test_map.o"
	@echo "... src/test/test_map.i"
	@echo "... src/test/test_map.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

