app_data <- read.csv("")
hash_data <- read.csv("")
merged <- data.frame(app_data[1], app_data[2], hash_data[2])
p <- ggplot2::ggplot(df, ggplot2::aes(data1[1])) 
p + ggplot2::geom_line(ggplot2::aes(y = data1[2], color = "Application Names")) 
p + ggplot2::geom_line(ggplot2::aes(y = data2[2], colour = "Network Names")) 
p + ggplot2::xlab("Name Index") + ggplot2::ylab("Wait Time [ns]") 
p + ggplot2::labs(colour = "Name Type")
p + ggplot2::theme(legend.position = "none")